[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "verisphere-semantic-dedupe"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]

